# Generated by Django 6.0.2 on 2026-02-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiros', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='retiro',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'PENDIENTE')), fields=('alumno',), name='unique_pendiente_por_alumno'),
        ),
    ]
