# Generated by Django 6.0.2 on 2026-02-14 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiros', '0002_retiro_unique_pendiente_por_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='retiro',
            name='grado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='retiros.grado'),
            preserve_default=False,
        ),
    ]
