# Generated by Django 6.0.2 on 2026-02-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiros', '0003_retiro_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='grado',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
