# Generated by Django 6.0.2 on 2026-02-16 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiros', '0005_alumno_en_colegio'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_estado',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
