# Generated by Django 6.0.2 on 2026-03-13 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiros', '0006_alumno_fecha_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(help_text='Ej: RUTA-01', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Ej: Buseta Norte o Nombre del Conductor', max_length=100)),
                ('conductor', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='transporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='retiros.transporte'),
        ),
        migrations.CreateModel(
            name='TurnoTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_COLA', 'En espera'), ('EMBARCANDO', 'Llamado / Abordando'), ('DESPACHADO', 'Ya se retiró')], default='EN_COLA', max_length=20)),
                ('hora_llegada', models.DateTimeField(auto_now_add=True)),
                ('hora_despacho', models.DateTimeField(blank=True, null=True)),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retiros.transporte')),
            ],
        ),
    ]
