# Generated by Django 6.0.2 on 2026-03-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiros', '0007_transporte_alumno_transporte_turnotransporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos_fotos/'),
        ),
    ]
