# Generated by Django 6.0.2 on 2026-03-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retiros', '0008_alumno_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grado',
            name='nivel',
        ),
        migrations.RemoveConstraint(
            model_name='retiro',
            name='unique_pendiente_por_alumno',
        ),
        migrations.DeleteModel(
            name='Nivel',
        ),
        migrations.DeleteModel(
            name='Retiro',
        ),
    ]
