# Generated by Django 6.0.2 on 2026-03-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiros', '0009_remove_grado_nivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporte',
            name='conductor',
        ),
        migrations.AlterField(
            model_name='transporte',
            name='codigo_unico',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
